/** Interface palette selected to complement the supplied SUIWU assets.
 * These are application tokens, not a claim of an official brand-color guide. */
export const brand = {
  parent: 'SUIWU 随物', child: 'ADDA', endorsement: 'SUIWU 随物旗下品牌',
  mark: '/assets/brand/suiwu-lotus-mark.png',
  parentEnglish: '/assets/brand/7846e5a3d39a673b230a47f52f4532ca.jpg',
  parentBilingual: '/assets/brand/99b0b4ec1602cc2760ffed5944b53444.jpg',
  parentScene: '/assets/brand/f78fd9085f6bde2ab8101aac1de72da9.jpg',
  water: '/assets/brand/4da38778134ae0fc6f4fb0046521903b.jpg'
} as const;

export const sharedTheme = `
:root{--canvas:#f3f6f3;--surface:#fff;--soft:#eaf2ed;--brand:#155d53;--brand-hover:#104c44;--ink:#173b35;--muted:#657a71;--line:#dce5df;--lotus:#d65e84;--lotus-soft:#fbeef2;--success:#267655;--warning:#886327;--danger:#ab354b;--night:#10292b;--night-panel:#163235;--night-line:#305153;--night-text:#e6f1ec;--night-muted:#a4bbb6;--radius:14px;--control-radius:9px;--shadow:0 12px 34px #153c3410;--font:Inter,"Noto Sans SC","PingFang SC","Microsoft YaHei",system-ui,sans-serif}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--canvas);color:var(--ink);font:14px/1.65 var(--font);-webkit-font-smoothing:antialiased}[hidden]{display:none!important}
a{color:var(--brand);text-decoration:none}a:hover{text-decoration:underline}button,input,textarea,select{font:inherit}button{cursor:pointer}button:disabled{cursor:not-allowed;opacity:.48}input,select,textarea{width:100%;max-width:100%;color:var(--ink);background:var(--surface);border:1px solid var(--line);border-radius:var(--control-radius);padding:11px 12px;min-height:44px}textarea{min-height:96px;resize:vertical}input[type=checkbox]{width:18px;height:18px;min-height:18px;accent-color:var(--brand)}input[type=file]{overflow:hidden}label{display:flex;flex-direction:column;gap:7px;font-size:12px;font-weight:600;color:var(--muted)}
button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible,[tabindex]:focus-visible{outline:3px solid var(--lotus);outline-offset:3px}
.btn,.ab-button,.primary-action,.step button,.offer button{display:inline-flex;align-items:center;justify-content:center;gap:8px;border:1px solid var(--brand);border-radius:var(--control-radius);min-height:42px;padding:10px 17px;background:var(--brand);color:white;font-weight:600;line-height:1.5;font-size:13px;text-decoration:none}
.btn:hover,.ab-button:hover,.primary-action:hover{background:var(--brand-hover);color:white}.btn.secondary,.ab-button.secondary,button.secondary{color:var(--brand);background:var(--surface);border:1px solid var(--line)}.btn.secondary:hover{background:var(--soft)}.btn.small{min-height:36px;padding:7px 12px;font-size:12px}
h1,h2,h3,h4,p{margin-top:0}h1{font-size:clamp(28px,3vw,40px);letter-spacing:-1.4px;line-height:1.25;font-weight:650;margin-bottom:14px}h2{font-size:19px;letter-spacing:-.4px;line-height:1.4;margin-bottom:17px}h3{font-size:15px;margin-bottom:13px}hr{border:0;border-top:1px solid var(--line);margin:26px 0}.muted,.fine,.lead{color:var(--muted)}.fine{font-size:12px;line-height:1.85}.lead{max-width:760px;font-size:14px;margin-bottom:27px}.eyebrow,.ab-kicker{font:600 10px/1.5 ui-monospace,monospace;letter-spacing:2px;color:var(--muted);margin-bottom:12px}
.card,.ab-card,.stat,.ab-stat,.form-card,.step{border:1px solid var(--line);background:var(--surface);padding:25px;border-radius:var(--radius);min-width:0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}.grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.fields .full{grid-column:1/-1}.actions,.row-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.row{border-bottom:1px solid var(--line);padding:17px 0;overflow-wrap:anywhere}.row:last-child{border-bottom:0}.row-title{font-weight:600;font-size:14px;display:flex;align-items:center;justify-content:space-between;gap:10px}.row-meta{font-size:12px;color:var(--muted);line-height:1.8;margin-top:7px}.badge,.chip{display:inline-flex;align-items:center;border:1px solid var(--line);background:var(--soft);color:var(--brand);border-radius:40px;padding:4px 9px;white-space:normal;font-size:10px;font-weight:650}.badge.warn{background:#fbf3e2;color:var(--warning);border-color:#ecdec0}.empty{padding:23px 12px;border:1px dashed var(--line);border-radius:10px;font-size:13px;color:var(--muted);line-height:1.8;background:var(--canvas)}.output{font-size:13px;line-height:1.85;overflow-wrap:anywhere;max-height:600px;overflow:auto}.notice,.status{font-size:12px;line-height:1.7;border-radius:10px;padding:12px 16px;background:var(--soft);border:1px solid var(--line);margin:0 0 23px;color:var(--brand)}.notice.error,.status.error{background:var(--lotus-soft);color:var(--danger);border-color:#edc8d3}.notice.success{background:var(--soft);color:var(--success)}.notice:empty,.status:empty{display:none}.skip-link{position:fixed;left:15px;top:-100px;z-index:100;background:white;padding:10px}.skip-link:focus{top:10px}.error-text,.ab-error{color:var(--danger);overflow-wrap:anywhere}
@media(max-width:800px){.grid,.grid.three{grid-template-columns:1fr}.card,.ab-card,.stat,.form-card,.step{padding:20px}.fields{gap:14px}.row-title{align-items:flex-start;flex-wrap:wrap}h1{font-size:29px}}@media(max-width:420px){.fields{grid-template-columns:1fr}.fields .full{grid-column:auto}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
