export function consumerApp(storeSlug: string, sourceTitle: string, sourceToken: string): void {
  const $ = (id: string): HTMLElement => document.getElementById(id)!;
  let language: 'en' | 'bn' = 'en'; let memberId = ''; let memberToken = ''; let demo = false; let consumerStatus: 'joined' | 'verified' | 'blocked' | '' = ''; let couponToken = ''; let offerCount = -1;
  let sending=false;const issued:Record<string,string>={};const storageKey='adda-member:'+storeSlug+':'+sourceToken;
  function remember():void {try{sessionStorage.setItem(storageKey,JSON.stringify({memberId,memberToken,issued}));}catch{$('member-storage-note').textContent=language==='en'?'Storage is unavailable. Keep this tab open and save your access information securely.':'স্টোরেজ নেই। এই ট্যাব খোলা রাখুন।';}}
  const words = {
    en: { store:'Store', title:'Welcome to ADDA MATE', source:'Campaign source', intro:'Join with a campaign link. Marketing updates are optional and require a separate channel choice.', contact:'Email or phone', consent:'I agree to receive marketing updates', channel:'Updates via', select:'Select a channel', join:'Join ADDA MATE', missing:'A campaign source link is required to register.', joined:'Registration saved. Keep this page open for verification and offers.', verify:'Verify contact', code:'Verification code', test:'Demo verification code: 000000. Production requires a configured verification provider.', blocked:'Verification needs an external provider; no verified status is claimed.', verifyButton:'Verify', verified:'Contact verified in test mode.', offers:'Available offers', noOffers:'No active offers for this campaign.', issue:'Get coupon', coupon:'Present this coupon token at the store:', error:'Request failed' },
    bn: { store:'দোকান', title:'ADDA MATE-এ স্বাগতম', source:'ক্যাম্পেইনের উৎস', intro:'ক্যাম্পেইনের লিংক দিয়ে যোগ দিন। বিপণন বার্তা ঐচ্ছিক এবং আলাদা চ্যানেল নির্বাচন করতে হবে।', contact:'ইমেইল বা ফোন', consent:'আমি বিপণন বার্তা পেতে সম্মত', channel:'বার্তার মাধ্যম', select:'মাধ্যম বেছে নিন', join:'ADDA MATE-এ যোগ দিন', missing:'নিবন্ধনের জন্য ক্যাম্পেইনের লিংক প্রয়োজন।', joined:'নিবন্ধন সংরক্ষিত হয়েছে। যাচাই ও অফারের জন্য এই পৃষ্ঠা খোলা রাখুন।', verify:'যোগাযোগ যাচাই করুন', code:'যাচাইকরণ কোড', test:'ডেমো যাচাইকরণ কোড: 000000। প্রোডাকশনে আলাদা যাচাই সেবা প্রয়োজন।', blocked:'যাচাই সেবা সংযুক্ত নেই; যাচাইকৃত হিসেবে দেখানো হচ্ছে না।', verifyButton:'যাচাই করুন', verified:'টেস্ট মোডে যোগাযোগ যাচাই হয়েছে।', offers:'উপলব্ধ অফার', noOffers:'এই ক্যাম্পেইনে সক্রিয় অফার নেই।', issue:'কুপন নিন', coupon:'দোকানে এই কুপন টোকেন দেখান:', error:'অনুরোধ ব্যর্থ হয়েছে' }
  };
  function translate(): void {
    const w=words[language]; $('member-controls').hidden=!memberId; $('revoke-marketing').textContent=language==='en'?'Unsubscribe from marketing':'বিপণন বার্তা বন্ধ করুন'; $('clear-member').textContent=language==='en'?'Forget this tab':'এই ট্যাবের তথ্য মুছুন'; document.documentElement.lang=language; $('lang-en').setAttribute('aria-pressed',String(language==='en')); $('lang-bn').setAttribute('aria-pressed',String(language==='bn')); $('store').textContent=w.store+': '+storeSlug; $('title').textContent=w.title; $('intro').textContent=sourceToken?w.source+': '+sourceTitle+'. '+w.intro:w.missing; $('join').hidden=!sourceToken || !!memberId; $('contact-text').textContent=w.contact; $('consent-text').textContent=w.consent; $('channel-text').textContent=w.channel; ($('channel') as HTMLSelectElement).options[0].textContent=w.select; $('join-button').textContent=w.join; $('verify-title').textContent=w.verify; $('verify-note').textContent=demo?w.test:w.blocked; $('code-label').textContent=w.code; $('verify-button').textContent=w.verifyButton; $('offers-title').textContent=w.offers; if(consumerStatus) $('result').textContent=w[consumerStatus]+(consumerStatus==='joined'?' ID: '+memberId:''); if(offerCount===0) $('offers').textContent=w.noOffers; document.querySelectorAll('#offers button').forEach(button=>button.textContent=w.issue); if(couponToken) $('coupon-result').textContent=w.coupon+' '+couponToken;
  }
  async function send(path: string, body: unknown): Promise<any> { const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const b=await r.json(); if(!r.ok) throw new Error(b.message||b.error_code||words[language].error); return b; }
  $('lang-en').addEventListener('click',()=>{ language='en'; translate(); }); $('lang-bn').addEventListener('click',()=>{ language='bn'; translate(); });
  $('optin').addEventListener('change',()=>{ $('channel-label').hidden=!( $('optin') as HTMLInputElement).checked; });
  $('join').addEventListener('submit',ev=>{ ev.preventDefault(); void (async()=>{ if(sending)return;sending=true;($('join-button') as HTMLButtonElement).disabled=true;try { if(!sourceToken) throw new Error(words[language].missing); const optin=($('optin') as HTMLInputElement).checked; const channel=($('channel') as HTMLSelectElement).value; if(optin&&!channel) throw new Error(words[language].channel); const b=await send('/api/members/register',{source_token:sourceToken,contact:($('contact') as HTMLInputElement).value,marketing_opt_in:optin,channel:optin?channel:null,language,notice_version:'adda-mate-v1'}); memberId=b.member.id; memberToken=b.member_token; remember(); consumerStatus='joined'; translate(); ($('join-button') as HTMLButtonElement).disabled=true; $('verify-step').hidden=false; $('offers-step').hidden=false; await offers(); } catch(error){ $('result').textContent=error instanceof Error?error.message:words[language].error; } finally {sending=false;($('join-button') as HTMLButtonElement).disabled=!!memberId;} })(); });
  $('verify-form').addEventListener('submit',ev=>{ ev.preventDefault(); void (async()=>{ try { const b=await send('/api/members/verify',{member_id:memberId,member_token:memberToken,code:($('code') as HTMLInputElement).value}); consumerStatus=b.contact_verified?'verified':'blocked'; translate(); } catch(error){ $('result').textContent=error instanceof Error?error.message:words[language].error; } })(); });
  async function offers(): Promise<void> { try { const r=await fetch('/api/public/offers?source_token='+encodeURIComponent(sourceToken)); const b=await r.json(); if(!r.ok) throw new Error(b.error_code); const list=b.items||[]; offerCount=list.length; $('offers').replaceChildren(); if(!list.length){ $('offers').textContent=words[language].noOffers; return; } for(const offer of list){ const div=document.createElement('div'); div.className='offer'; const strong=document.createElement('strong'); strong.textContent=offer.name; const p=document.createElement('p'); p.textContent=offer.terms; const button=document.createElement('button'); button.textContent=words[language].issue; button.addEventListener('click',()=>{ void (async()=>{ if(button.disabled)return;button.disabled=true;try { const b=await send('/api/public/coupons/issue',{source_token:sourceToken,member_id:memberId,member_token:memberToken,offer_id:offer.id}); couponToken=b.coupon.token;issued[offer.id]=couponToken;remember();translate(); button.disabled=true; } catch(error){ $('coupon-result').textContent=error instanceof Error?error.message:words[language].error;button.disabled=false; } })(); }); if(issued[offer.id]){couponToken=issued[offer.id];button.disabled=true;translate();}div.append(strong,p,button); $('offers').append(div); } } catch(error){ $('offers').textContent=error instanceof Error?error.message:words[language].error; } }
  $('revoke-marketing').addEventListener('click',()=>{void Promise.all(['email','sms','whatsapp'].map(channel=>send('/api/consents/revoke',{member_id:memberId,member_token:memberToken,channel,notice_version:'adda-mate-v1'}))).then(()=>{$('result').textContent=language==='en'?'Marketing consent revoked.':'বিপণনের সম্মতি প্রত্যাহার করা হয়েছে।';}).catch(error=>{$('result').textContent=error.message;});});
  $('clear-member').addEventListener('click',()=>{try{sessionStorage.removeItem(storageKey);}catch{}location.reload();});
  try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(saved && typeof saved.memberId==='string' && typeof saved.memberToken==='string'){void send('/api/public/member-state',{member_id:saved.memberId,member_token:saved.memberToken}).then(state=>{memberId=saved.memberId;memberToken=saved.memberToken;if(saved.issued && typeof saved.issued==='object')for(const [id,token]of Object.entries(saved.issued))if(typeof token==='string')issued[id]=token;consumerStatus=state.contact_verified?'verified':'joined';($('join-button')as HTMLButtonElement).disabled=true;$('verify-step').hidden=false;$('offers-step').hidden=false;translate();void offers();}).catch(()=>{try{sessionStorage.removeItem(storageKey);}catch{}});}}catch{}
  void fetch('/api/healthz').then(r=>r.json()).then(h=>{ demo=h.mode!=='production'; $('consumer-mode').hidden=!demo;$('consumer-mode').textContent=demo?'DEMO / TEST · Synthetic records only · No real benefits or delivery':''; translate(); }).catch(()=>{ translate(); }); translate();
}
